import { strings } from "./strings";

const email = "thejenniferhaggerty@gmail.com";
const github = "https://github.com/JennHaggerty/hobnail";

/**
 * ALL of the app's settings.
 *
 * @todo move sensitive data to .env.local and add tests for prodction env
 */
export const config = {
  title: "Open Library App",
  description:
    "Generated by create next app and tapping into the Open Library Search API",
  api: "https://openlibrary.org/search.json?q=",
  apiParams: "&limit=50",
  apiViewMoreLinkKey: "https://openlibrary.org{key}",
  apiBookCover: "https://covers.openlibrary.org/b/olid/{key}-L.jpg",
  mailto: "mailto:" + email,
  mainNav: {
    id: "main-menu",
    items: [
      {
        title: strings.search,
        id: "search-page",
        onClick: () => location.reload(),
      },
      {
        title: strings.github,
        id: "github-page",
        url: github,
        external: true,
      },
    ],
  },
  copyright: (
    <>
      Created by{" "}
      <a href="https://jenniferhaggerty.com" target="_blank">
        Jennifer
      </a>{" "}
      for{" "}
      <a href="https://livefront.com" target="_blank">
        Livefront
      </a>{" "}
      using{" "}
      <a href="https://openlibrary.org" target="_blank">
        Open Library
      </a>
      .
    </>
  ),
};
